services:
  enshrouded:
    image: mbround18/enshrouded-docker:latest
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    environment:
      PRESET: "Normal"
    ports:
      - "8211:8211"
      - "27015:27015"
    volumes:
      - ./tmp:/home/steam/enshrouded
