services:
  enshrouded:
    image: mbround18/enshrouded-docker:latest
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    environment:
      NAME: "My Enshrouded Server" # Optional, Name of the server
      SET_GROUP_USER_PASSWORD: "securepassword" # Optional, Password for the server
#      ADMIN_PASSWORD: "adminpassword" # Optional, Admin password for the server
#      SAVE_DIRECTORY: ./savegame # Optional, Save directory for the game
#      LOG_DIRECTORY: ./logs # Optional, Log directory for the server
#      SERVER_IP: 0.0.0.0 # Optional, IP address for the server
#      GAME_PORT: 15636 # Optional, Game port for the server
#      QUERY_PORT: 15637 # Optional, Query port for the server
#      SLOT_COUNT: 16 # Optional, Number of slots for the server
      RUST_LOG: "debug"
      AUTO_UPDATE: "1"
      AUTO_UPDATE_SCHEDULE: "*/3 * * * *"
    ports:
      - "15636:15636/udp"
      - "15636:15636/tcp"
      - "15637:15637/udp"
      - "15637:15637/tcp"
    volumes:
      - ./tmp:/home/steam/enshrouded
