name: Docker Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      
jobs:
  Release:
    uses: mbround18/gh-reusable/.github/workflows/docker-release.yaml@main
    with: 
      image: mbround18/enshrouded-docker
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      
