name: Docker Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  Release:
    uses: mbround18/gh-reusable/.github/workflows/docker-release.yaml@mbround18-patch-2
    with:
      image: mbround18/enshrouded-docker
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
