name: Docker Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled]

jobs:
  Release:
    uses: mbround18/gh-reusable/.github/workflows/docker-release.yaml@v0.0.4
    with:
      image: mbround18/enshrouded-docker
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
